### ISSUE TITLE
Work with ZMQ PHP server

### ISSUE THREAD

**Issue by phatpham9** [zeromq/JSMQ#7]
Now I have a ZMQ server that is written in PHP. How can JSMQ work with it? Does it need a websocket server? Please help!

**Comment by somdoron** [comment]
you need to use https://github.com/zeromq/zwssock/ (CZMQ) or https://github.com/somdoron/NetMQ.Websockets (NETMQ)

I guess you can wrap the zwssock to use in php

**Comment by phatpham9** [comment]
Thank you for replying. I will learn them more.

**Comment by krisrok** [comment]
out of sheer interest, i guess you are using this binding https://github.com/mkoppanen/php-zmq ? what is your impression so far? are you using zmq on other platforms too, or are you aiming for only php + js?
i'm asking because the binding is fairly outdated and my web developer and me have to review it some time soon, so i'm eager to hear opinions :)

**Comment by phatpham9** [comment]
Hi Krisrok,

You're right. Zmq helped to improve much on our system's performance, both server and client. We used NetMQ for Windows client, also for iOS and Android version. Now the HTML5 version is being developed.
